### ISSUE TITLE
Segmentation fault on peeling

### ISSUE THREAD

**Issue by klakhoti** [jeshi96/parbutterfly#1]
Hi,

Thank you for the code, it is a great help. I am trying to run the peeling operation. However, I get a segmentation fault for both vertex and edge peeling. I parallelize using OPENMP and use all 36 threads on the machine.

It looks like the edge peeling is running but giving a segmentation fault later. However, the vertex peeling gives a segmentation fault in the first round of peeling itself. Also, the butterfly count when 
doing per-vertex counting is incorrect (per-edge counting gives correct results; reference - values reported in the paper). 

Dataset used: DBLP (from Koblenz Network Collection, same as the arxiv paper).
PeelType: HASH
CountType: HASH

Kindly look into the issue.
![pb_issue1](https://user-images.githubusercontent.com/24485095/69577399-1a9f4780-0f83-11ea-95aa-2cb086c8f00c.JPG)

**Comment by jeshi96** [comment]
Thanks for catching these bugs! I just pushed two changes that I believe should fix things -- the most recent fix is for the vertex peeling using hashing problem, and the second most recent fix is for the edge multiple rounds problem. They work on Cilk in my system, and should work on openmp too (please let me know if this isn't the case).

**Comment by klakhoti** [comment]
Thanks Jessica. I wasn't expecting a fix this quick, amazing. Will test and
let you know.
